#!/usr/bin/env python3

from subprocess import check_output, call
import os
import subprocess

block_button = os.environ['BLOCK_BUTTON'] if 'BLOCK_BUTTON' in os.environ else None
block_button = int(block_button) if block_button else None

if block_button == 1:
    call(['light', '-A', '10'])
elif block_button == 3:
    call(['light', '-U', '10'])


brightness = check_output(['light'], universal_newlines=True)

icon = "<span font='FontAwesome'>\uf185</span> "
print("{}{}%".format(icon, int(round(float(brightness)))))
print("{}{}%".format(icon, int(round(float(brightness)))))
print("")
