#!/bin/bash

# Number of docker containers running
count=$(docker ps -q | wc -l | sed -r 's/^0$//g')

if $showip ; then
    # Recent docker container IP
    recent_ip=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $(docker ps -ql))
    echo "$label $count: $recent_ip"
else
    echo "$label $count"
fi
