#!/bin/bash

INSTANCE="${BLOCK_INSTANCE:-1}"

URGENT_VALUE=70

# Hardcoded to this system
# grep 'model name' /proc/cpuinfo | wc -l
CPUS=$(grep 'model name' /proc/cpuinfo | wc -l)

LOAD=$(cat /proc/loadavg)
if [[ "${LOAD}" != "" ]]; then
  ONE_MIN=$(echo ${LOAD} | awk -F ' ' '{print $1}')
  FIV_MIN=$(echo ${LOAD} | awk -F ' ' '{print $2}')
  FIF_MIN=$(echo ${LOAD} | awk -F ' ' '{print $3}')

  function scale_colorize() {
    PERC=$(echo "scale=0; ${1} * 100 / ${CPUS}" | bc -l)
    if [[ "${PERC}" -ge "100" ]]; then
      printf "<span background='#dc322f'>%2d</span>" ${PERC}
    elif [[ "${PERC}" -ge "${URGENT_VALUE}" ]]; then
      printf "<span background='#839496'>%2d</span>" ${PERC}
    else
      printf "${PERC}"
    fi
  }

  ONE_PERC=$(scale_colorize "${ONE_MIN}")
  FIV_PERC=$(scale_colorize "${FIV_MIN}")
  FIF_PERC=$(scale_colorize "${FIF_MIN}")

  echo "$label ${ONE_PERC}/${FIV_PERC}/${FIF_PERC}"

fi
